name: DecoyBlocks
main: Fishrock123.DecoyBlocks.DecoyBlocks
version: 0.4.1 ALPHA (1C6)
dev-url: http://dev.bukkit.org/server-mods/decoyblocks/
description: >
    DecoyBlocks:
commands:
    db:
        description:
        usage: