name: DecoyBlocks
main: com.fishrock123.decoyblocks.DecoyBlocks
version: 0.7 BETA (1G0)
author: Fishrock123
dev-url: http://dev.bukkit.org/server-mods/decoyblocks/
commands:
    db:
        permission: decoyblocks
permissions:
  decoyblocks.*:
    description: Gives access to all DecoyBlocks commands
    children:
      decoyblocks.decoys: true
      decoyblocks.log: true
      decoyblocks.restore: true
      decoyblocks.clear: true
      decoyblocks.reload: true
      decoyblocks.teleport: true
      decoyblocks.search: true
      decoyblocks.test: true
  decoyblocks.decoys:
    description: Allows you to place and remove decoys.
    default: op
  decoyblocks.log:
    description: Allows you to see the log.
    default: op
  decoyblocks.restore:
    description: Allows you to restore the decoys.
    default: op
  decoyblocks.clear.log:
    description: Allows you to clear the log.
    default: op
  decoyblocks.clear:
    description: (DANGEROUS) Allows you to remove all decoys at once.
    default: op
    children:
      decoyblocks.clear.log: true
  decoyblocks.save:
    description: Allows you to save the decoys.
    default: op
  decoyblocks.reload:
    description: Allows you to reload DecoyBlocks.
    default: op
    children:
      decoyblocks.save: true
  decoyblocks.teleport:
    description: Allows you to teleport to the nearest broken block for the specified player.
    default: op
  decoyblocks.search:
    description: Allows you to search for decoys broken per-player.
    default: op
  decoyblocks.test:
    description: Allows you to properly test DecoyBlocks' functions.
    default: op