name: DecoyBlocks
main: Fishrock123.DecoyBlocks.DecoyBlocks
version: 0.5.2 ALPHA (1D8)
dev-url: http://dev.bukkit.org/server-mods/decoyblocks/
description: >
    DecoyBlocks:
commands:
    db:
        description:
        usage: